import Config
config :ash, policies: [show_policy_breakdowns?: true]

# Configure your database
config :revstack, Revstack.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "revstack_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :revstack, RevstackWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "SGpbhHVwqvs3BZ/vI1u6MxwlmCUPmIGWddTeRSCQY0SrOCIQlvMqNC2B15VYNGy/",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:revstack, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:revstack, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :revstack, RevstackWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/revstack_web/router\.ex$"E,
      ~r"lib/revstack_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable enhanced HEEx debugging info surfaced by Tidewave to AI agents
config :phoenix_live_view,
  debug_heex_annotations: true,
  debug_attributes: true

# Enable dev routes for dashboard and mailbox
config :revstack, dev_routes: true, token_signing_secret: "MduSjK8bg5vmRM3yRCAErmrftwaxOH8P"

# Disable geolocation in development (only enabled in production)
config :revstack, geolocation_provider: :disabled

# Dev admin credentials (override via env vars if desired)
config :revstack,
  admin_email: System.get_env("ADMIN_EMAIL", "admin@revenuelink.net"),
  admin_password: System.get_env("ADMIN_PASSWORD", "adminpassword123!")

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
