defmodule Revstack.Repo.Migrations.AddReferrerToVisitorPageVisits do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:visitor_page_visits) do
      add(:referrer, :text)
    end
  end

  def down do
    alter table(:visitor_page_visits) do
      remove(:referrer)
    end
  end
end
