defmodule Revstack.Repo.Migrations.AddVisitorTracking do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:visitors, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:ip_address, :text, null: false)
      add(:ip_location_city, :text)
      add(:ip_location_region, :text)
      add(:ip_location_country, :text)
      add(:ip_location_latitude, :float)
      add(:ip_location_longitude, :float)
      add(:user_agent, :text)
      add(:referrer, :text)
      add(:first_visited_at, :utc_datetime, null: false)
      add(:last_visited_at, :utc_datetime, null: false)
      add(:visit_count, :bigint, null: false, default: 0)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create unique_index(:visitors, [:ip_address], name: "visitors_unique_ip_index")

    create table(:visitor_page_visits, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:path, :text, null: false)
      add(:full_url, :text)
      add(:query_string, :text)
      add(:method, :text)
      add(:visited_at, :utc_datetime, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(
        :visitor_id,
        references(:visitors,
          column: :id,
          name: "visitor_page_visits_visitor_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)
    end

    alter table(:leads) do
      add(:visitor_id, :uuid)
      add(:request_ip, :text)
      add(:request_user_agent, :text)
    end

    alter table(:estimate_requests) do
      add(:visitor_id, :uuid)
      add(:request_ip, :text)
      add(:request_user_agent, :text)
    end
  end

  def down do
    alter table(:estimate_requests) do
      remove(:request_user_agent)
      remove(:request_ip)
      remove(:visitor_id)
    end

    alter table(:leads) do
      remove(:request_user_agent)
      remove(:request_ip)
      remove(:visitor_id)
    end

    drop(constraint(:visitor_page_visits, "visitor_page_visits_visitor_id_fkey"))

    drop(table(:visitor_page_visits))

    drop_if_exists(unique_index(:visitors, [:ip_address], name: "visitors_unique_ip_index"))

    drop(table(:visitors))
  end
end
